[package]
id = "j6wtadrs2qgnvijqpadk336bkb2xsezr"
name = "days_and_knights"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.2-dev"

[dependencies]
orbit_camera = { deployment = "16errWVktnKFdrbFofKCAE" }

[messages.Action.Input]
descritpion = "Input messages for heros movement and actions"

[messages.Action.fields]
point_ray_origin = "Vec3"
point_ray_direction = "Vec3"
primary_attack = "Bool"
secondary_attack = "Bool"
health_potion = "Bool"
mana_potion = "Bool"
interact = "Bool"
jump = "Bool"
sprint = "Bool"