[package]
id = "j6wtadrs2qgnvijqpadk336bkb2xsezr"
name = "days_and_knights"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.2-dev"

[dependencies]
orbit_camera = { deployment = "16errWVktnKFdrbFofKCAE" }
unit_schema = { deployment = "hfv4W9UuED197vKDfol7g" }
character_movement = { deployment = "2TMMtfgQwAplpQtmAfyzci" }

[messages.Movement.Input]
descritpion = "Input messages for heros movement"

[messages.Movement.fields]
screen_ray_origin = "Vec3"
screen_ray_direction = "Vec3"

[messages.Action.Input]
descritpion = "Input messages for heros actions"

[messages.Action.fields]
attack = "Bool"
drink = "Bool"
interact = "Bool"
jump = "Bool"
sprint = "Bool"

[enums.PhysicsLayer]
descritpion = "Physics layers"
members = { Ground = "Ground", Character = "Character", Interactable = "Interactable" }

[components]
physics_layer = { type = "PhysicsLayer", name = "Physics Layers Component", description = "Physics layers used to filter physics collisions", attributes = ["Debuggable"] }
